### DISCUSSION TITLE
Difficulty getting Wallaby to connect to Selenium

### DISCUSSION THREAD

**Discussion by aidalgol** [keathley/wallaby#599] [Q&A] [answered]
I am trying to add end-to-end testing to my Phoenix application using Wallaby, but Wallaby does not seem to be connecting to Selenium.

This is the error:
```
  1) feature Log In/Out button is "Log In" (PaddyWeb.LandingPageTest)
     test/paddy_web/end_to_end/landing_page_test.exs:7
     ** (RuntimeError) Wallaby had an internal issue with HTTPoison:
     %HTTPoison.Error{id: nil, reason: :econnrefused}
     stacktrace:
       (wallaby 0.28.0) lib/wallaby/httpclient.ex:50: Wallaby.HTTPClient.make_request/5
       (wallaby 0.28.0) lib/wallaby/selenium.ex:93: Wallaby.Selenium.start_session/1
       (wallaby 0.28.0) lib/wallaby.ex:82: Wallaby.start_session/1
       (wallaby 0.28.0) lib/wallaby/feature.ex:152: Wallaby.Feature.Utils.start_session/2
       (elixir 1.10.4) lib/enum.ex:1400: anonymous fn/3 in Enum.map/2
       (elixir 1.10.4) lib/enum.ex:2116: Enum.map/2
       test/paddy_web/end_to_end/landing_page_test.exs:3: PaddyWeb.LandingPageTest.__ex_unit_setup_0/1
       test/paddy_web/end_to_end/landing_page_test.exs:1: PaddyWeb.LandingPageTest.__ex_unit__/2
```

Wallaby config in `test.exs`:
```elixir
config :wallaby,
  driver: Wallaby.Selenium,
  otp_app: :paddy,
  selenium: [
    remote_url: "http://selenium:4444/"
  ]
```

I run `mix` via a wrapper script checks for Selenium being ready via the `/status` endpoint, so Selenium is definitely up and running by the time Wallaby is started.  Am I setting the Selenium for Wallaby incorrectly?  (I also had this setup working with Hound, which I was evaluating prior to trying Wallaby.)

<details>
<summary><code>docker-compose.yml</code></summary>

```yaml
version: "3.3"
services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
    depends_on:
      - db
      - selenium
    environment:
      - POSTGRES_HOST=db
    volumes:
      - type: bind
        source: .
        target: /paddy
      - type: volume
        source: dot-mix
        target: /home/paddy/.mix
      - type: volume
        source: dot-hex
        target: /home/paddy/.hex

  db:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data

  selenium:
    image: selenium/standalone-firefox:4
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm

volumes:
  db:
  dot-mix:
  dot-hex:
```

The Selenium status check in the wrapper script for the `phoenix` image, as mentioned above.
```bash
echo 'Waiting for Selenium to be ready...'
while ! [ "$(curl -sSL http://selenium:4444/status | jq -r '.value.ready')" == "true" ]; do
  sleep 2
done
```
</details>
